
services:
  ledger:
    build: .
    env_file: 
      - /home/ledgeradmin/ledger/env/ledger.env
    volumes:
      - /home/ledgeradmin/ledger/data:/data
    ports:
      - "127.0.0.1:8001:5000"
    restart: unless-stopped

