category_name = {
    "beauty": "Beauty & Personal Care",
    "education": "Childcare & Education",
    "credit_card": "Credit Card Payments",
    "dining": "Dining Out",
    "entertainment": "Entertainment",
    "gifts": "Gifts & Donations",
    "grocery": "Grocery",
    "health": "Health & Fitness",
    "home_maintenance": "Home Maintenance",
    "insurance": "Insurance",
    "loans": "Loan Payments",
    "pets": "Pets",
    "rent": "Rent",
    "savings": "Savings & Investments",
    "shopping": "Shopping",
    "subscriptions": "Subscriptions & Memberships",
    "transport": "Transportation",
    "travel": "Travel",
    "utilities": "Utilities",
    "work": "Work",
    "other": "Other"
}