name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key and known hosts
        run: |
          mkdir -p ~/.ssh
          echo "$VPS_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 134.122.56.15 >> ~/.ssh/known_hosts
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa root@134.122.56.15 << 'EOF'
            set -e  # Остановит скрипт при ошибке
            cd ~/friendly-octo-spork
            git reset --hard HEAD
            git clean -fd
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart gunicorn
          EOF